version: "3"

services:
  lnd_bitcoin:
    image: btcpayserver/lnd:0.4.2.0
    container_name: btcpayserver_lnd_bitcoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: "${NBITCOIN_NETWORK:-regtest}"
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        rpclisten=127.0.0.1:10008
        rpclisten=0.0.0.0:10009
        bitcoin.node=bitcoind
        bitcoind.rpchost=bitcoind:43782
        bitcoind.zmqpath=tcp://bitcoind:28332
        externalip=${BTCPAY_HOST}:9735
        alias=${LIGHTNING_ALIAS}
        noencryptwallet=1
        notls=1
    ports:
      - "9735:9735"
    expose:
      - "8080"
      - "9735"
    volumes:
      - "lnd_bitcoin_datadir:/data"
      - "bitcoin_datadir:/deps/.bitcoin"
    links:
      - bitcoind

  btcpayserver:
    environment:
      BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=http://lnd_bitcoin:8080/;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon;allowinsecure=true"
      BTCPAY_BTCEXTERNALLNDGRPC: "type=lnd-grpc;server=${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon"
    volumes:
      - "lnd_bitcoin_datadir:/etc/lnd_bitcoin"
    links:
      - lnd_bitcoin

  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        zmqpubrawtx=tcp://0.0.0.0:28332
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtxlock=tcp://0.0.0.0:28332
        zmqpubhashblock=tcp://0.0.0.0:28332
    expose:
      - "28332"
  
  nginx:
    links:
      - "lnd_bitcoin"
    volumes:
      - "lnd_bitcoin_datadir:/lnd"
  nginx-gen:
    links:
      - "lnd_bitcoin"
    volumes:
      - "lnd_bitcoin_datadir:/lnd"

volumes:
  lnd_bitcoin_datadir: