version: "3"

services:
  groestlcoind:
    restart: unless-stopped
    container_name: btcpayserver_groestlcoind
    image: groestlcoin/docker-groestlcoin:2.21.1
    environment:
      GROESTLCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
      - "43782"
      - "39388"
    volumes:
      - "groestlcoin_datadir:/data"
  nbxplorer:
    environment:
      NBXPLORER_CHAINS: "grs"
      NBXPLORER_GRSRPCURL: http://groestlcoind:43782/
      NBXPLORER_GRSNODEENDPOINT: groestlcoind:39388
    volumes:
      - "groestlcoin_datadir:/root/.groestlcoin"
  btcpayserver:
    environment:
      BTCPAY_CHAINS: "grs"
      BTCPAY_GRSEXPLORERURL: http://nbxplorer:32838/
volumes:
  groestlcoin_datadir:
