version: "3"

services:
  lnd_litecoin:
    image: btcpayserver/lnd:0.4.2.0
    container_name: btcpayserver_lnd_litecoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "ltc"
      LND_ENVIRONMENT: "${NBITCOIN_NETWORK:-regtest}"
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        litecoin.node=litecoind
        litecoind.rpchost=litecoind:43782
        litecoind.zmqpath=tcp://litecoind:28332
        externalip=${BTCPAY_HOST}:9736
        alias=${LIGHTNING_ALIAS}
        noencryptwallet=1
        notls=1
    ports:
      - "9736:9735"
    expose:
      - "8080"
      - "9736"
    volumes:
      - "lnd_litecoin_datadir:/data"
      - "litecoin_datadir:/deps/.litecoin"
    links:
      - litecoind

  btcpayserver:
    environment:
      BTCPAY_LTCLIGHTNING: "type=lnd-rest;server=http://lnd_litecoin:8080/;macaroonfilepath=/etc/lnd_litecoin/admin.macaroon;allowinsecure=true"
    volumes:
      - "lnd_litecoin_datadir:/etc/lnd_litecoin"
    links:
      - lnd_litecoin

  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        zmqpubrawtx=tcp://0.0.0.0:28332
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtxlock=tcp://0.0.0.0:28332
        zmqpubhashblock=tcp://0.0.0.0:28332
    expose:
      - "28332"

volumes:
  lnd_litecoin_datadir: