version: "3"

services:
  lnd_litecoin:
    image: btcpayserver/lnd:0.5-beta
    container_name: btcpayserver_lnd_litecoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "ltc"
      LND_ENVIRONMENT: "${NBITCOIN_NETWORK:-regtest}"
      LND_EXPLORERURL: "http://nbxplorer:32838/"
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        litecoin.node=litecoind
        litecoind.rpchost=litecoind:43782
        litecoind.zmqpubrawblock=tcp://litecoind:28332
        litecoind.zmqpubrawtx=tcp://litecoind:28333
        externalip=${BTCPAY_HOST}:9736
        alias=${LIGHTNING_ALIAS}
        adminmacaroonpath=/data/admin.macaroon
        noseedbackup=1
        notls=1
    ports:
      - "9736:9735"
    expose:
      - "8080"
      - "9736"
    volumes:
      - "lnd_litecoin_datadir:/data"
      - "litecoin_datadir:/deps/.litecoin"
      - "nbxplorer_datadir:/root/.nbxplorer"
    links:
      - nbxplorer
      - litecoind

  btcpayserver:
    environment:
      BTCPAY_LTCLIGHTNING: "type=lnd-rest;server=http://lnd_litecoin:8080/;macaroonfilepath=/etc/lnd_litecoin/admin.macaroon;allowinsecure=true"
    volumes:
      - "lnd_litecoin_datadir:/etc/lnd_litecoin"
    links:
      - lnd_litecoin

  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    expose:
      - "28332"
      - "28333"

volumes:
  lnd_litecoin_datadir: