version: "3"

services:
  clightning_litecoin:
    image: nicolasdorier/clightning:0.0.0.20
    container_name: btcpayserver_clightning_litecoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/litecoin
        bitcoin-rpcconnect=litecoind
        bind-addr=0.0.0.0:9735
        announce-addr=${BTCPAY_HOST}:9736
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=ltc
    volumes:
      - "clightning_litecoin_datadir:/root/.lightning"
      - "litecoin_datadir:/etc/litecoin"
    ports:
      - "9736:9735"
    links:
      - litecoind
  btcpayserver:
    environment:
      BTCPAY_LTCLIGHTNING: "/etc/clightning_litecoin/lightning-rpc"
    volumes:
      - "clightning_litecoin_datadir:/etc/clightning_litecoin"
    links:
      - clightning_litecoin
volumes:
  clightning_litecoin_datadir: