version: "3"
# If your machine has less than 1GB of memory, use this

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=50
        maxmempool=50
  electrumx:
    environment:
      - CACHE_MB=50
      - MAX_SESSIONS=100
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=50
        maxmempool=50
  dogecoind:
    environment:
      DOGECOIN_EXTRA_ARGS: |
        dbcache=50
        maxmempool=50
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=50
        maxmempool=50
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=50
        maxmempool=50
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=50
        maxmempool=50
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=50
        maxmempool=50
  monacoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        dbcache=50
        maxmempool=50
exclusive:
  - memory
