version: "3"
services:
  nnostr-relay:
    restart: unless-stopped
    image: kukks/nnostr-relay:v0.0.17
    container_name: nnostr-relay
    environment:
      NOSTR_CONNECTIONSTRINGS__RelayDatabase: User ID=postgres;Host=postgres;Port=5432;Database=nnostr
      ASPNETCORE_URLS: "http://0.0.0.0:80"
    links:
      - postgres
      - btcpayserver
    volumes:
      - "nnostr_datadir:/datadir"
  btcpayserver:
    environment:
      BTCPAY_EXTERNALSERVICES: "Nostr Relay:nostr;"
volumes:
  nnostr_datadir:
