services:
  zcash_walletd:
    restart: unless-stopped
    image: hhanh00/zcash-walletd:latest
    environment:
      NOTIFY_TX_URL: http://btcpayserver:49392/zcashlikedaemoncallback/tx?cryptoCode=zec&hash=
      ROCKET_DB_PATH: /data/zec-wallet2.db
      CONFIG_PATH: /data/config2.json
      LWD_URL: http://lightwalletd:9067
    expose:
      - "8000"
    volumes:
    - "zec_wallet:/data"

  btcpayserver:
    environment:
      BTCPAY_ZEC_DAEMON_URI: http://zcash_walletd:8000
      BTCPAY_ZEC_WALLET_DAEMON_URI: http://zcash_walletd:8000
      BTCPAY_ZEC_WALLET_DAEMON_WALLETDIR: /root/zec_wallet
    volumes:
      - "zec_wallet:/root/zec_wallet"

  zebra:
    container_name: zebra
    image: zfnd/zebra
    platform: linux/amd64
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "4"
          memory: 16G
    volumes:
      - zebrad-cache:/home/zebra/.cache/zebra
    tty: true
    environment:
      - ZEBRA_RPC_PORT=8232
      - ENABLE_COOKIE_AUTH=false
    ports:
      - "8232:8232"
    #networks:
    #  - generated_default

  lightwalletd:
    image: electriccoinco/lightwalletd
    platform: linux/amd64
    depends_on:
      zebra:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          cpus: "4"
          memory: 16G
    environment:
      - LWD_GRPC_PORT=9067
      - LWD_HTTP_PORT=9068
    configs:
      - source: lwd_config
        target: /etc/lightwalletd/zcash.conf
    volumes:
      - lwd-cache:/var/lib/lightwalletd/db
    #! This setup with `--no-tls-very-insecure` is only for testing purposes.
    #! For production environments, follow the guidelines here:
    #! https://github.com/zcash/lightwalletd#production-usage
    command: >
      --no-tls-very-insecure
      --grpc-bind-addr=0.0.0.0:9067
      --http-bind-addr=0.0.0.0:9068
      --zcash-conf-path=/etc/lightwalletd/zcash.conf
      --data-dir=/var/lib/lightwalletd/db
      --log-file=/dev/stdout
      --log-level=7
    ports:
      - "127.0.0.1:9067:9067" # gRPC
      - "127.0.0.1:9068:9068" # HTTP

configs:
  lwd_config:
    file: ./zcash.conf

volumes:
  zec_wallet:
  zec_data:
  zebrad-cache:
    driver: local

  lwd-cache:
    driver: local

exclusive:
  - zcash-node
