version: "3"
services:
  btcpayserver:
    restart: always
    image: nicolasdorier/btcpayserver:1.0.1.80
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-yourname@example.com}
      BTCPAY_LTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_CHAINS: "ltc,btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
    links:
    - nbxplorer
    - postgres
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    ports:
    - "80:49392"
  nbxplorer:
    restart: always
    image: nicolasdorier/nbxplorer:1.0.1.32
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "ltc,btc"
      NBXPLORER_LTCRPCURL: http://litecoind:43782/
      NBXPLORER_LTCNODEENDPOINT: litecoind:39388
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "litecoin_datadir:/root/.litecoin"
    - "bitcoin_datadir:/root/.bitcoin"
    links:
    - litecoind
    - bitcoind
  postgres:
    restart: always
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  litecoind:
    restart: always
    container_name: btcpayserver_litecoind
    image: nicolasdorier/docker-litecoin:0.15.1
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
    - "43782"
    - "39388"
    volumes:
    - "litecoin_datadir:/data"
  bitcoind:
    restart: always
    container_name: btcpayserver_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
    - "43782"
    - "39388"
    volumes:
    - "bitcoin_datadir:/data"
volumes:
  postgres_datadir: 
  btcpay_datadir: 
  nbxplorer_datadir: 
  litecoin_datadir: 
  bitcoin_datadir: 
