version: "3"
services:
  btcpayserver:
    restart: always
    image: nicolasdorier/btcpayserver:1.0.1.80
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-yourname@example.com}
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "/etc/clightning_bitcoin/lightning-rpc"
    links:
    - nbxplorer
    - postgres
    - clightning_bitcoin
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "clightning_bitcoin_datadir:/etc/clightning_bitcoin"
    ports:
    - "80:49392"
  nbxplorer:
    restart: always
    image: nicolasdorier/nbxplorer:1.0.1.32
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "bitcoin_datadir:/root/.bitcoin"
    links:
    - bitcoind
  postgres:
    restart: always
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  bitcoind:
    restart: always
    container_name: btcpayserver_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
    - "43782"
    - "39388"
    volumes:
    - "bitcoin_datadir:/data"
  clightning_bitcoin:
    image: nicolasdorier/clightning:0.0.0.3
    container_name: btcpayserver_clightning_bitcoin
    restart: always
    environment:
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind
        ipaddr=${BTCPAY_HOST}
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=btc
    volumes:
    - "clightning_bitcoin_datadir:/root/.lightning"
    - "bitcoin_datadir:/etc/bitcoin"
    ports:
    - "9735:9735"
    links:
    - bitcoind
volumes:
  postgres_datadir: 
  btcpay_datadir: 
  nbxplorer_datadir: 
  bitcoin_datadir: 
  clightning_bitcoin_datadir: 
