version: "3"
services:
  btcpayserver:
    restart: unless-stopped
    image: nicolasdorier/btcpayserver:1.0.2.94
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      BTCPAY_LTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_CHAINS: "ltc,btc"
      BTCPAY_LTCLIGHTNING: "type=clightning;server=unix://etc/clightning_litecoin/lightning-rpc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "type=clightning;server=unix://etc/clightning_bitcoin/lightning-rpc"
    links:
    - nbxplorer
    - postgres
    - clightning_litecoin
    - clightning_bitcoin
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "clightning_litecoin_datadir:/etc/clightning_litecoin"
    - "clightning_bitcoin_datadir:/etc/clightning_bitcoin"
    ports:
    - "80:49392"
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.2.31
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "ltc,btc"
      NBXPLORER_LTCRPCURL: http://litecoind:43782/
      NBXPLORER_LTCNODEENDPOINT: litecoind:39388
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "litecoin_datadir:/root/.litecoin"
    - "bitcoin_datadir:/root/.bitcoin"
    links:
    - litecoind
    - bitcoind
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  litecoind:
    restart: unless-stopped
    container_name: btcpayserver_litecoind
    image: nicolasdorier/docker-litecoin:0.15.1
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
    - "43782"
    - "39388"
    volumes:
    - "litecoin_datadir:/data"
  clightning_litecoin:
    image: nicolasdorier/clightning:aeafe4dbe7d5c61f664c18417698866b0d70252f-2
    container_name: btcpayserver_clightning_litecoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      LIGHTNINGD_CHAIN: ltc
      LIGHTNINGD_EXPLORERURL: "http://nbxplorer:32838/"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/litecoin
        bitcoin-rpcconnect=litecoind
        bind-addr=0.0.0.0:9735
        announce-addr=${BTCPAY_HOST}:9736
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=ltc
    volumes:
    - "clightning_litecoin_datadir:/root/.lightning"
    - "litecoin_datadir:/etc/litecoin"
    - "nbxplorer_datadir:/root/.nbxplorer"
    ports:
    - "9736:9735"
    links:
    - nbxplorer
    - litecoind
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: nicolasdorier/docker-bitcoin:0.16.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
    - "43782"
    - "39388"
    volumes:
    - "bitcoin_datadir:/data"
  clightning_bitcoin:
    image: nicolasdorier/clightning:aeafe4dbe7d5c61f664c18417698866b0d70252f-2
    container_name: btcpayserver_clightning_bitcoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      LIGHTNINGD_CHAIN: btc
      LIGHTNINGD_EXPLORERURL: "http://nbxplorer:32838/"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind
        announce-addr=${BTCPAY_HOST}:9735
        bind-addr=0.0.0.0:9735
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=btc
    volumes:
    - "clightning_bitcoin_datadir:/root/.lightning"
    - "bitcoin_datadir:/etc/bitcoin"
    - "nbxplorer_datadir:/root/.nbxplorer"
    ports:
    - "9735:9735"
    links:
    - nbxplorer
    - bitcoind
volumes:
  postgres_datadir: 
  btcpay_datadir: 
  nbxplorer_datadir: 
  litecoin_datadir: 
  clightning_litecoin_datadir: 
  bitcoin_datadir: 
  clightning_bitcoin_datadir: 
